# Centralized training on CartPole-v1 (upper bound baseline, 1 worker with full batch)
env = "CartPole-v1"
num-server-rounds = 312
num-workers = 1
num-byzantine = 0
method = "centralized"
batch-size = 160
use-adaptive-communication = false
